Add support for VHost in connection string.
Azure/azure-functions-rabbitmq-extension pull request #171
Opened 2021-08-27 13:37 UTC by kentonbmax

Add support for parsing vhost from connection property and supplying it to the rabbit client.

2021-08-27 13:38 UTC, kentonbmax commented
Fix for #81

2021-10-25 15:53 UTC, kentonbmax commented
@pragnagopa  is this repo still active? There is not a lot of activity here yet this is still in use?

2021-10-25 17:09 UTC, pragnagopa commented
> @pragnagopa is this repo still active? There is not a lot of activity here yet this is still in use?

Apologies for late response here. Yes, this repo is still active. Tagging @JatinSanghvi @lpapudippu to follow up

2021-10-27 11:51 UTC, JatinSanghvi requested changes

2021-10-27 11:51 UTC, JatinSanghvi commented on src/Services/RabbitMQService.cs
> +            if (!string.IsNullOrWhiteSpace(connectionString))
I have a couple of asks:
1. Why not merge the `if (rabbitUri.AbsolutePath != "/")` with line 68?
2. Line 99 is not safe as the hostname might contain the VHost string. Use `connectionFactory.Uri = new Uri(rabbitUri.GetLeftPart(UriPartial.Authority));` instead.
3. I am new to Rabbit MQ. The connection string used in code example on https://www.cloudamqp.com/docs/dotnet.html#publish would set the Virtual Host to `%2f` but either the VHost is not present here or its value is `/` (need to check which one). I found the connection string examples in **Appendix A: Examples** on https://www.rabbitmq.com/uri-spec.html. A correct fix here would be to URI decode the path and then set the VHost and other properties.
4. Please update the test case in file `test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQServiceTests.cs` to ensure that expected value of VHost string is assigned to `connectionFactory.VirtualHost`.

I also think that we should update the `RabbitMQService` constructor to explicitly consume VHost as an argument. May need to ensure that it does not cause a breaking change. Anyhow that can be done as a separate step.

2021-10-27 12:29 UTC, JatinSanghvi commented on src/Services/RabbitMQService.cs
> +            if (!string.IsNullOrWhiteSpace(connectionString))
Hi @kentonbmax, I created a test app with code as below. I did not require to manually extract VHost from the connection string. It was set automatically by `ConnectionFactory` on setting its `Uri` property. I think I am using same RabbitMQ client library version as this extension, but am on .NET Core 3.1 instead of 2.2. Let me know if I am missing something here.

**Program**

```cs
// CloudAMQP URL in format amqp://user:pass@hostName:port/vhost
var url = "amqp://user%61:%61pass@host:10000/v%2fhost";

var factory = new ConnectionFactory
{
    Uri = new Uri(url)
};

Console.WriteLine(factory.UserName);
Console.WriteLine(factory.Password);
Console.WriteLine(factory.HostName);
Console.WriteLine(factory.Port);
Console.WriteLine(factory.VirtualHost);
```

**Output**
```text
usera
apass
host
10000
v/host
```

2021-10-28 12:51 UTC, kentonbmax commented on src/Services/RabbitMQService.cs
> +            if (!string.IsNullOrWhiteSpace(connectionString))
I did try my connection string with /env in my existing azure functions where the connection string is an environment variable and the trigger failed to connect. I believe the issue is in the constructor resetting the values. So my question is why explicitly set anything other then connectionString?

2022-01-29 11:31 UTC, JatinSanghvi commented on src/Services/RabbitMQService.cs
> +            if (!string.IsNullOrWhiteSpace(connectionString))
As mentioned in https://github.com/Azure/azure-functions-rabbitmq-extension/issues/81#issuecomment-708888734, connection-string is the workaround for lack of support for virtual host parameter. I think the extension supports both combinations of binding parameters (connection string or passing each piece of information individually) and we will be keeping it like this. I will need to close this PR and reopen #95.

2022-01-29 11:31 UTC, JatinSanghvi commented
Closing this one in favor of #95.

2022-01-29 11:31 UTC, closed without merging