Add new parameter to specify the vhost to use on RabbitMQ server.
Azure/azure-functions-rabbitmq-extension pull request #180
Opened 2022-01-29 19:43 UTC by Socolin

See https://www.rabbitmq.com/vhosts.html for more details.
It was already possible to use this using the ConnectionString, this allow it
to be used when specifying host/user/password

Fixes: #81

2022-01-29 19:44 UTC, Socolin commented
I've updated the code with the latest version since previous PR was closed 
https://github.com/Azure/azure-functions-rabbitmq-extension/pull/95#issuecomment-1024896888

I did no manual tests with the updated code. Unit tests are passing.

2022-01-31 05:41 UTC, JatinSanghvi commented
> I've updated the code with the latest version since previous PR was closed [#95 (comment)](https://github.com/Azure/azure-functions-rabbitmq-extension/pull/95#issuecomment-1024896888)
> 
> I did no manual tests with the updated code. Unit tests are passing.

Thanks, I will get it manually tested.

2022-01-31 06:21 UTC, JatinSanghvi requested changes

2022-01-31 06:21 UTC, JatinSanghvi commented on src/RabbitMQAttribute.cs
> +        [AppSetting]
Delete line 54. `AppSetting` attribute will require the value for `VirtualHost` parameter to always come from settings file. We add that restriction only for parameters who values might be secrets.

2022-01-31 06:21 UTC, JatinSanghvi commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQOptionsTests.cs
> +                { nameof(option.VirtualHost), option.VirtualHost },
Swapping lines 23 and 24 should make the unit tests run successfully.

2022-01-31 10:22 UTC, JatinSanghvi commented
@Socolin, I have done manual E2E validation of the changes. If you can make the requested changes, I will approved and merge the PR.

2022-02-03 03:53 UTC, JatinSanghvi commented
@Socolin, we just introduced `enableSsl` parameter to both trigger and output bindings. With this PR, there will be yet another parameter introduced. In general, based on my discussion with other developers, most of them use connection strings instead of passing individual tokens (username, password, hostname, port, etc.) in their bindings. The other official extensions only have support for connection strings though something like (account-name + account-key) was possible for them. Hence, I have decided to remove the attribute-properties for individual parts. The reason why we need to introduce `vhost` parameter in this PR is to overcome the limitation of only working with default `vhost` when user passes username, password, etc. individually. Supporting only the connection string should avoid the need of this parameter. Considering this, I have decided to close the PR. Let me know if you have any comments.. thanks for the PR though.

2022-02-03 03:53 UTC, closed without merging