Samples for different azure function runtimes
Azure/azure-functions-rabbitmq-extension pull request #67
Opened 2019-09-17 14:11 UTC by geekwhocodes

Added "samples" folder where users can add samples for different azure function runtimes. 

Added samples for :

- CSharp
  * Queue Output
  * Queue Trigger

- Python
  * Queue Output
  * Queue Trigger

2019-09-17 14:12 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=67) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=67) before we can accept your contribution.<br/><br/>:x: geekwhocodes [sign now](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=67)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-functions-rabbitmq-extension?pullRequest=67) it.</sub>

2019-10-30 20:35 UTC, fabiocav commented
Thank you for submitting this! We'll be reviewing this ASAP.

/cc @pragnagopa @jeffhollan

2019-11-16 04:02 UTC, pragnagopa requested changes
Thanks for the PR. Added few comments.

2019-11-16 04:02 UTC, pragnagopa commented on samples/Python/proxies.json
> +  "proxies": {}
This sample is not adding any proxies. Please delete.

2019-11-16 04:02 UTC, pragnagopa commented on samples/Python/QueueTrigger/sample.dat
> +sample queue data
this file is not needed unless you plan to include test scripts that use this file to invoke the function

2019-11-16 04:02 UTC, pragnagopa commented on samples/Python/QueueTrigger/readme.md
> +# RabbitMQ QueueTrigger - Python
Readme included in the repo and wiki are descriptive. Readme per sample is not needed

2019-11-16 04:02 UTC, pragnagopa commented on samples/Python/QueueOutput/sample.dat
> +{
delete this file

2019-11-16 04:02 UTC, pragnagopa commented on samples/Python/QueueOutput/readme.md
> +
same here. Readme per sample is not needed

2019-11-16 04:02 UTC, pragnagopa commented on samples/CSharp/AzureFunctionsRabbitMQSamples/example.settings.json
> +    "FUNCTIONS_WORKER_RUNTIME": "dotnet",
Please create a folder 'Azure.Functions.Samples' under Samples folder and then sub directories per language:  `CSharp` , `Python` etc

2019-11-16 04:02 UTC, pragnagopa commented on samples/CSharp/AzureFunctionsRabbitMQSamples/OutputToQueue.cs
> +        {
Please combine queue samples into one file

2019-11-17 15:23 UTC, geekwhocodes commented
Thanks for the feedback, I will remove unnecessary files asap.

2019-12-09 06:54 UTC, geekwhocodes commented
This is being redundant. I will add these examples in wiki itself.

2020-07-21 12:36 UTC, closed without merging