Added durability setting for queues
Azure/azure-functions-rabbitmq-extension pull request #78
Opened 2019-11-13 13:31 UTC by swtrse

Also provided unit tests for the new functions.

This is an alternative implementation for durable queues to https://github.com/Azure/azure-functions-rabbitmq-extension/pull/74.

2019-11-13 13:31 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=78) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=78) before we can accept your contribution.<br/><br/>:x: swtrse [sign now](https://cla.opensource.microsoft.com/Azure/azure-functions-rabbitmq-extension?pullRequest=78)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-functions-rabbitmq-extension?pullRequest=78) it.</sub>

2019-11-16 04:16 UTC, pragnagopa requested changes
Thanks for PR! Please update this PR rebasing changes on the dev branch. Also, please undo formatting changes

2019-11-27 02:07 UTC, pragnagopa reviewed
Added few comments. Thanks!

2019-11-27 02:07 UTC, pragnagopa commented on src/Config/RabbitMQExtensionConfigProvider.cs
>          {
This overload is needed for binding to RabbitMqClient. Please undo the delete

2019-11-27 02:07 UTC, pragnagopa commented on src/Utility.cs
> -            {
nit: Undo and please add a comment `//ignore exception`

2019-11-27 02:07 UTC, pragnagopa commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQClientBuilderTests.cs
> -            mockServiceFactory.Verify(m => m.CreateService(It.IsAny<string>(), Constants.LocalHost, "guest", "guest", 5672), Times.Exactly(1));
Undo. This is needed

2019-11-27 02:07 UTC, pragnagopa commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQClientBuilderTests.cs
> +        {
Change these tests to use [Theory] and take expected result as input paramenter

2019-11-27 02:07 UTC, pragnagopa commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQConfigProviderTests.cs
> +        {
Same here. Please use [Theory]

2019-11-27 02:07 UTC, pragnagopa commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQConfigProviderTests.cs
> +        [InlineData(false, false)]
Also, add E2E sample here: https://github.com/Azure/azure-functions-rabbitmq-extension/blob/dev/test/WebJobs.Extensions.RabbitMQ.Samples/RabbitMQSamples.cs

2019-11-29 18:58 UTC, zorge commented
Will that update work with trigger binding or only with direct model binding? I right now cannot utilize the extension because it I need to listen to a durable queue on another server but cannot...because of the hardcoded durability value.

2019-12-03 08:48 UTC, swtrse reviewed
It should work with trigger binding too. If not I did miss some thing. I just try to adapt the implementation (using .netcore 3.0, nullable reference types and alternate code format rules that prevent the abuse of the space character as indent character) I made for my company into this code.

2019-12-03 08:48 UTC, swtrse commented on test/WebJobs.Extensions.RabbitMQ.Tests/RabbitMQClientBuilderTests.cs
> -            mockServiceFactory.Verify(m => m.CreateService(It.IsAny<string>(), Constants.LocalHost, "guest", "guest", 5672), Times.Exactly(1));
If used the test will fail since this method is not used any more. Instead the new method with the queueDurable paramater will be called.

2020-04-23 17:56 UTC, fabiocav commented
@swtrse are you sill intending to update this PR? It has been idle for a few months now. Thanks!

2020-04-24 16:44 UTC, tronelius commented
@fabiocav would be nice if this (functionality) went into the extension, with this PR or with help from a member of ms!

2020-05-08 21:00 UTC, closed without merging

2020-06-24 10:41 UTC, swtrse commented
FYI I have no intention to update this PR again. I already did that 2 times and nothing happened. This PR only got mentioned when the project whent forward and the PR did become incompatible with the current codebase. I have no intention to participate any further in that project. My company moved to out own implementation so that we could add new and needed features in a acceptable timeframe.